public class hoe {
    public static void main(String[] args) {
        String [] qt = { "/Users/xtemper//Desktop/poi-bin/poi-5.2.3.jar",
        "/Users/xtemper//Desktop/poi-bin/poi-examples-5.2.3.jar",
        "/Users/xtemper//Desktop/poi-bin/poi-excelant-5.2.3.jar",
        "/Users/xtemper//Desktop/poi-bin/poi-javadoc-5.2.3.jar",
        "/Users/xtemper//Desktop/poi-bin/poi-ooxml-5.2.3.jar",
        "/Users/xtemper//Desktop/poi-bin/poi-ooxml-full-5.2.3.jar",
        "/Users/xtemper//Desktop/poi-bin/poi-ooxml-lite-5.2.3.jar",
        "/Users/xtemper//Desktop/poi-bin/poi-scratchpad-5.2.3.jar",
        "/Users/xtemper//Desktop/poi-bin/ooxml-lib/commons-compress-1.21.jar",
        "/Users/xtemper//Desktop/poi-bin/ooxml-lib/commons-logging-1.2.jar",
        "/Users/xtemper//Desktop/poi-bin/ooxml-lib/curvesapi-1.07.jar",
        "/Users/xtemper//Desktop/poi-bin/ooxml-lib/jakarta.activation-2.0.1.jar",
        "/Users/xtemper//Desktop/poi-bin/ooxml-lib/jakarta.xml.bind-api-3.0.1.jar",
        "/Users/xtemper//Desktop/poi-bin/ooxml-lib/slf4j-api-1.7.36.jar",
        "/Users/xtemper//Desktop/poi-bin/ooxml-lib/xmlbeans-5.1.1.jar",
        "/Users/xtemper//Desktop/poi-bin/lib/commons-codec-1.15.jar",
        "/Users/xtemper//Desktop/poi-bin/lib/commons-collections4-4.4.jar",
        "/Users/xtemper//Desktop/poi-bin/lib/commons-io-2.11.0.jar",
        "/Users/xtemper//Desktop/poi-bin/lib/commons-math3-3.6.1.jar",
        "/Users/xtemper//Desktop/poi-bin/lib/log4j-api-2.18.0.jar",
        "/Users/xtemper//Desktop/poi-bin/lib/SparseBitSet-1.2.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-anim-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-awt-util-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-bridge-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-codec-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-constants-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-css-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-dom-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-ext-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-gvt-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-i18n-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-parser-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-script-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-shared-resources-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-svg-dom-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-svggen-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-svgrasterizer-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-transcoder-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-util-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/batik-xml-1.14.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/bcpkix-jdk15on-1.70.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/bcprov-jdk15on-1.70.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/bcutil-jdk15on-1.70.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/fontbox-2.0.26.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/graphics2d-0.40.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/pdfbox-2.0.26.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/xml-apis-1.4.01.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/xml-apis-ext-1.3.04.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/xmlgraphics-commons-2.6.jar",
        "/Users/xtemper//Desktop/poi-bin/auxiliary/xmlsec-3.0.0.jar"};
        for(int i = 0 ; i < qt.length ; i++)
        System.out.println("chmod +x " + qt[i]);
    }
}
